pipeline {
    agent any
    tools { 
        maven 'maven-3.6.3'
    }
    stages {
        stage ('Initialize') {
            steps {
                    echo "Init"
            }
        }
		
        stage ('Maven Build') {
			 agent {
					docker {
					  image 'maven:3.6.3'
					}
				 }		
            steps {
                bat 'mvn clean package'
                echo 'Shir finished Building her Project'
            }
		}
			
      stage ('Run') {
            steps {
                //bat 'java -cp target/helloworld-1.1.jar com.coveros.demo.helloworld.HelloWorld'
				bat 'docker build -t target/helloworld:latest .'
                echo 'Shir is finishing Running her Project'  
            }
      }      
        
        
        
    }
}
